### ISSUE TITLE
Is this being maintained?

### ISSUE THREAD

**Issue by arjun-mehta10** [cisco/exanic-software#57]
Prior to Sept 15, 2021, there have been regular commits and releases via this repository. But there have been none subsequently. Have you shifted to any internal repo? How do we get the updates? I noticed that the FDK 2.9.0 has been released [here](https://software.cisco.com/download/home/286326311), but no download options for the exanic-software package.

**Comment by alexisfrjp** [comment]
No, FDK is the hardware package.
The libs and kmod are still 2.7.1.

It doesn't even compile on RHEL 8...
https://exablaze.com/downloads/yum/redhat/el8/x86_64/
 
Lots of links in their doc are dead, I contacted them many times, no answer.
You should avoid buying NICs that haven't got updates for years with customer service being dead silent for weeks.

**Comment by badipietro** [comment]
Hello,

This repository is being maintained by Cisco staff going forward.    Active work is in progress by the Cisco staff to merge and release changes.    The currently tested builds for 2.7.1 are in the release notes:

https://github.com/cisco/exanic-software/blob/master/RELEASE-NOTES.txt

The Cisco team is aware that the driver does not compile for latest CentOS 8.4 kernel.  Note that the driver/libraries do compile for the tested release (CentOS 8.4 (kernel 4.18.0-305).  

As the monitoring of this issue list is in transition would recommend that if you need the latest RHEL/CentOS release to build/compile, have a pressing issue to report, or have questions,  please also open a Cisco TAC case here:

https://cisco.com/support

The SmartNIC links and documentation in the github repository will be updated in a future release. 

In the meantime,  here is the updated link for the SmartNIC user guide:

https://www.cisco.com/c/en/us/td/docs/dcn/smartnics/user-guide/index.html

The SmartNIC landing page is here:
https://www.cisco.com/c/en/us/support/interfaces-modules/nexus-smartnic/series.html

The latest firmware for the SmartNICs is located here:

https://software.cisco.com/download/home/286326311?catid=268437717

The latest release of the SmartNIC Firmware Development Kit (FDK) is 2.9.0 and located here: https://software.cisco.com/download/home/286329394/type/286326855/release/exanic_fdk_2.9.0

Best Regards,
Bob
