### ISSUE TITLE
exanic_find_port_by_interface_name fails for X100 on RHEL8/9

### ISSUE THREAD

**Issue by Alexxstud** [cisco/exanic-software#67]
Hello, if somebody is monitoring the issues here.

The problem:
When the application runs with exasock and an accelerated TCP socket calls connect() it passes through [exa_socket_update_interfaces](https://github.com/cisco/exanic-software/blob/master/libs/exasock/sockets.c#L261) then to [exanic_ip_acquire](https://github.com/cisco/exanic-software/blob/master/libs/exasock/sockets.c#L297-L298), correctly determines the interface from the dst IP, but fails to map the network interface to ExaNIC port. More specifically, the problem is with libexanic - [exanic_find_port_by_interface_name](https://github.com/cisco/exanic-software/blob/master/libs/exanic/config.c#L202) fails to provide device:port for the interface
despite this interface surely belongs to ExaNIC card and exanic-config lists it correctly. In other words, the mapping of
ports to the network interfaces in [exanic_t if_index](https://github.com/cisco/exanic-software/blob/master/libs/exanic/exanic.h#L59) is 100% correct, but the reverse mapping of the interface to the port fails due to
[ioctl(fd, EXAIOCGIFINFO, &ifr)](https://github.com/cisco/exanic-software/blob/master/libs/exanic/config.c#L249) call returning -1 (ioctl there actually seems to be the OS one with some wrappers). This problem arises on two different machines each with the same ExaNIC X100 card and under both RHEL8 and RHEL9 OS. The version
of exanic-software under consideration is the lastest: release 2.7.3, 13 Oct. 2022.

Calling bind() to INADDR_ANY or to the interface IP doesn't help. Is there any subtlety with exasock? Or some specific function must be called after a socket creation and before connect()? The application uses usual AF_INET sockets, exasock is called as a wrapper as written in the [documentation](https://exablaze.com/docs/exanic/user-guide/sockets/#usage).

**Comment by sudeep30m** [comment]
I'm facing the exact same issue on Rocky 9.1 OS. I'm using ExaNIC X25 card with version 2.7.3 and with the latest firmware (firmware date is 20220210). @Alexxstud Please reply if you were able to resolve this issue

**Comment by Alexxstud** [comment]
Hello, @sudeep30m The only solution I have found so far is to through the library calls, edit [exanic_find_port_by_interface_name](https://github.com/cisco/exanic-software/blob/master/libs/exanic/config.c#L202) function and reinstall the driver.

**Comment by kumarsameer** [comment]
@Alexxstud  what to edit in the `exanic_find_port_by_interface_name` function ?

**Comment by danfruehauf** [comment]
See attached fix, gets the job done for me - the `ioctl` is now handled and the device is probed correctly.
